In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import json

# Load the dataset
data_2015 = pd.read_excel("/content/drive/My Drive/Data Visualization/Data Visualization Project/2015_small.xlsx")

# Load the JSON file with code mappings
with open("/content/drive/My Drive/Data Visualization/Data Visualization Project/2015_codes.json", 'r') as file:
    codes_2015 = json.load(file)

In [4]:
# Replace codes in the dataset for all columns with corresponding mappings in the JSON file
for column in data_2015.columns:
    if column in codes_2015:
        data_2015[column] = data_2015[column].astype(str).map(codes_2015[column]).fillna(data_2015[column])

# Display the transformed data for the 'education_2003_revision' column as a test
data_2015.head()

,resident_status,education_1989_revision,education_2003_revision,education_reporting_flag,month_of_death,sex,detail_age_type,detail_age,age_substitution_flag,age_recode_52,...,record_condition_18,record_condition_19,record_condition_20,race,bridged_race_flag,race_imputation_flag,race_recode_3,race_recode_5,hispanic_origin,hispanic_originrace_recode
0,RESIDENTS,NaN,high school graduate or GED completed,2003 revision of education item on certificate,1,Male,Years,84,NaN,80 - 84 years,...,NaN,NaN,NaN,1,NaN,NaN,White,White,100,Non - Hispanic white
1,RESIDENTS,NaN,Bachelor’s degree,2003 revision of education item on certificate,1,Male,Years,70,NaN,70 - 74 years,...,NaN,NaN,NaN,1,NaN,NaN,White,White,100,Non - Hispanic white
2,RESIDENTS,NaN,high school graduate or GED completed,2003 revision of education item on certificate,1,Female,Years,91,NaN,90 - 94 years,...,NaN,NaN,NaN,1,NaN,NaN,White,White,100,Non - Hispanic white
3,RESIDENTS,NaN,high school graduate or GED completed,2003 revision of education item on certificate,1,Female,Years,40,NaN,40 - 44 years,...,NaN,NaN,NaN,3,NaN,NaN,Races other than White or Black,American Indian,100,Non - Hispanic other races
4,RESIDENTS,NaN,Associate degree,2003 revision of education item on certificate,1,Female,Years,89,NaN,85 - 89 years,...,NaN,NaN,NaN,1,NaN,NaN,White,White,100,Non - Hispanic white

In [5]:
data_2015['race_recode_5'].head()

0              White
1              White
2              White
3    American Indian
4              White
Name: race_recode_5, dtype: object